### ISSUE TITLE
API check-node-version v4.0.1 terminates with throwing an error on Windows/nodist

### ISSUE THREAD

**Issue by yuki-takei** [parshap/check-node-version#35]
Environment
------------

| item     | version |
| ---      | --- |
|OS        |Windows 10|
|node.js   |10.15.2|
|npm       |6.1.0|
|check-node-version|4.0.1|

How to reproduce?
---------------------------

1. Install [nodist](https://github.com/nullivex/nodist) on Windows
1. Install node v10
    ```bash
    nodist + 10    
    ```

1. run check-node-version
    ```bash
    check-node-version --print
    ```

What happens? 
---------------------

- An error is occured about npx
    ```
    check-node-version\cli.js:45
        throw err;
        ^
    
    Error: Command failed: "npx --version"
    
    stderr:
    'npx' �́A�����R�}���h�܂��͊O���R�}���h�A
    ����\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B
    
    
    original error message:
    Command failed: npx --version
    'npx' �́A�����R�}���h�܂��͊O���R�}���h�A
    ����\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B
    
    
        at exec (C:\Users\Yuki\Documents\Projects\Growi\growi\node_modules\check-node-version\index.js:58:21)
        at ChildProcess.exithandler (child_process.js:301:5)
        at ChildProcess.emit (events.js:189:13)
        at maybeClose (internal/child_process.js:970:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
    ```
- Error message is broken

What is the expected result? 
-------------------------------------------

- Terminate without throwing an error that is the same behavior at v3.3.0 or below
- (Avoid garbled characters if possible)

Note
----

- nodist does not bundle npx
- In the case of check-node-version v3.3.0 
    ```
    check-node-version --print
    node: 10.15.2
    npm: 6.1.0
    'npx' �́A�����R�}���h�܂��͊O���R�}���h�A
    ����\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B
    yarn: 1.13.0
    ```

I would like to use check-node-version programmable API, v4.0.1 throws an error, therefore the first argument of callback func 'error' is filled and I couldn't get the result.

**Comment by rasenplanscher** [comment]
@yuki-takei 
What is your output when you run `npx --version` directly, in `cmd` and `powershell` respectively?

**Comment by rasenplanscher** [comment]
@parshap 
I think the problem here is that the error message is localized and therefore the naive check for the Windows error message concerning the tool being unknown just doesn't catch it.

That means we need a more robust error handler for missing executables on Windows 🤔 too bad we don't have a specific error code as on *nix...

I have an idea that I'll try out in the coming days 🤔

**Comment by yuki-takei** [comment]
@rasenplanscher 

```
>npx --version
'npx' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
```

This is the localized message to japanese that should be

> 'npx' is not recognized as an internal or external command, operable program or batch file.

in English.

**Comment by rasenplanscher** [comment]
@yuki-takei 
Thanks 🙂

**Comment by rasenplanscher** [comment]
@yuki-takei 
I'm trying to reproduce the garbled text but for some reason, even with the system set to Japanese I still get English error messages 🤔 Could you try a few things for me?

Please, run `chcp 65001` (supposed to change the current codepage to utf8), then `check-node-version --print`, and let me know the output you get.

Please, put the following in a js-file, execute it, and let me know the out:
```
require("child_process").exec("nxp --version", (err) => { console.error(err.message) })
```


Finally, the same with this, please:
```
require("child_process").exec("chcp 65001; nxp --version", (err) => { console.error(err.message) })
```

**Comment by yuki-takei** [comment]
@rasenplanscher 

> Please, run chcp 65001 (supposed to change the current codepage to utf8), then check-node-version --print, and let me know the output you get.

```
>chcp 65001
Active code page: 65001
>check-node-version --print
npx: not installed
node: 10.15.2
yarn: 1.13.0
npm: 6.1.0
```

> Please, put the following in a js-file, execute it, and let me know the out:

- test1.js
    ```
    require('child_process').exec('nxp --version', (err) => { console.error(err.message) });
    ```
- output
    ```
    >node test1.js
    Command failed: nxp --version
    'nxp' �́A�����R�}���h�܂��͊O���R�}���h�A
    ����\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B
    
    >chcp 65001
    Active code page: 65001
    
    >node test1.js
    Command failed: nxp --version
    'nxp' is not recognized as an internal or external command,
    operable program or batch file.
    ```

> Finally, the same with this, please:

- test2.js
    ```
    require("child_process").exec("chcp 65001; nxp --version", (err) => { console.error(err.message) })
    ```
- output
    ```
    >node test2.js
    Command failed: chcp 65001; nxp --version
    Parameter format not correct - 65001;
    ```

**Comment by yuki-takei** [comment]
@rasenplanscher 
This is interesting..

**test3.js**
```
require('child_process').exec('chcp 65001 && nxp --version', (err) => { console.error(err.message) });
```

```
>nxp --version
'nxp' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。

>chcp
現在のコード ページ: 932

>node test3.js
Command failed: chcp 65001 && nxp --version
'nxp' �́A�����R�}���h�܂��͊O���R�}���h�A
����\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B

>chcp
Active code page: 65001

>node test3.js
Command failed: chcp 65001 && nxp --version
'nxp' is not recognized as an internal or external command,
operable program or batch file.

``

**Comment by rasenplanscher** [comment]
@yuki-takei 
Thank you for your input. I'm sorry for the delay, been tied up in work.

That result is indeed interesting.

Please, try these scripts the same way, each in a fresh cmd/powershell with `chcp` before and after:
```js
const {exec} = require('child_process')
exec('chcp 65001', () => exec('nxp --version', (err) => { console.error(err.message) }))
```

```js
const {exec} = require('child_process')
let codepage = ''

exec('chcp', (_,stdout) => {
	codepage = stdout.match(/\d+/)[0]
	exec('chcp 65001', () => {
		exec('nxp --version', (err) => { console.error(err.message) })
		exec(`chcp ${codepage}`)
	})
})
```

**Comment by yuki-takei** [comment]
@rasenplanscher 

**test4.js**
```javascript
const { exec } = require('child_process');
exec('chcp 65001', () => { return exec('nxp --version', (err) => { console.error(err.message) }) });
```

```
>nxp --version
'nxp' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。

>chcp
現在のコード ページ: 932

>node test3.js
Command failed: nxp --version
'nxp' is not recognized as an internal or external command,
operable program or batch file.

>chcp
Active code page: 65001
```

**Comment by yuki-takei** [comment]
@rasenplanscher 

**test5-1.js**
```javascript
const { exec } = require('child_process');

let codepage = '';

exec('chcp', (_, stdout) => {
  codepage = stdout.match(/\d+/)[0];
  exec('chcp 65001', () => {
    exec('nxp --version', (err) => { console.error(err.message) });
    exec(`chcp ${codepage}`);
  });
});
```

```
>nxp --version
'nxp' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。

>chcp
現在のコード ページ: 932

>node test5-1.js

>chcp
現在のコード ページ: 932
```

The line 9 `exec(`chcp ${codepage}`);` seems to flush the screen, I couldn't to see the output to console. so I tried the following code.


**test5-2.js**
```javascript
const { exec } = require('child_process');

// let codepage = '';

exec('chcp', (_, stdout) => {
  codepage = stdout.match(/\d+/)[0];
  exec('chcp 65001', () => {
    exec('nxp --version', (err) => { console.error(err.message) });
    // exec(`chcp ${codepage}`);
  });
});
```

```
>nxp --version
'nxp' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。

>chcp
現在のコード ページ: 932

>node test5-2.js
Command failed: nxp --version
'nxp' is not recognized as an internal or external command,
operable program or batch file.

>chcp
Active code page: 65001
```

As the results of test5-1.js and test5-2, I think it works.

**Comment by rasenplanscher** [comment]
@yuki-takei 
Thanks a lot!

I'm not sure why you didn't see the error message without commenting the reset line 🤔
What about this variant:
```js
const {exec} = require('child_process')
let codepage = ''

exec('chcp', (_,stdout) => {
	codepage = stdout.match(/\d+/)[0]
	exec('chcp 65001', () => {
		exec('nxp --version', (err) => { 
			console.error(err.message)
			exec(`chcp ${codepage}`)
		})
	})
})
```

**Comment by rasenplanscher** [comment]
@yuki-takei 
Can you check out this project and see if `npm test` passes or fails? I'd hope it to fail but it might pass 🤔

**Comment by yuki-takei** [comment]
@rasenplanscher 
Sorry for the late reply.

It was failed after waiting long time (about 60 seconds).

```
c:\Users\Yuki\Documents\Projects\check-node-version>npm test

> check-node-version@4.0.1 test c:\Users\Yuki\Documents\Projects\check-node-version
> ava -v


  × bin » run with npx
  × bin » run with node
  × bin » run npm package
  √ index » check exactly requested tools want0 *nix (57.8s)
  √ index » check exactly requested tools want0 Win (55.7s)
  √ index » check exactly requested tools want1 *nix (55.7s)
  √ index » check exactly requested tools want1 Win (53.8s)
  √ index » check exactly requested tools want2 *nix (53.8s)
  √ index » check exactly requested tools want2 Win (51.9s)
  √ index » check exactly requested tools want3 *nix (51.8s)
  √ index » check exactly requested tools want3 Win (50s)
  √ index » check exactly requested tools want4 *nix (50s)
  √ index » check exactly requested tools want4 Win (48.3s)
  √ index » check exactly requested tools, failure want0 *nix (48.2s)
  √ index » check exactly requested tools, failure want0 Win (46.4s)
  √ index » check exactly requested tools, failure want1 *nix (46.4s)
  √ index » check exactly requested tools, failure want1 Win (44.8s)
  √ index » check exactly requested tools, failure want2 *nix (44.8s)
  √ index » check exactly requested tools, failure want2 Win (43.2s)
  √ index » check exactly requested tools, failure want3 *nix (43.1s)
  √ index » check exactly requested tools, failure want3 Win (41.4s)
  √ index » check exactly requested tools, failure want4 *nix (41.3s)
  √ index » check exactly requested tools, failure want4 Win (39.6s)
  √ index » check all tools if none is requested inst0 *nix (39.5s)
  √ index » check all tools if none is requested inst0 Win (37.7s)
  √ index » check all tools if none is requested inst1 *nix (37.7s)
  √ index » check all tools if none is requested inst1 Win (35.8s)
  √ index » check all tools if none is requested inst2 *nix (35.8s)
  √ index » check all tools if none is requested inst2 Win (33.9s)
  √ index » check all tools if none is requested inst3 *nix (33.9s)
  √ index » check all tools if none is requested inst3 Win (32s)
  √ index » check all tools if none is requested inst4 *nix (31.9s)
  √ index » check all tools if none is requested inst4 Win (30.1s)
  √ index » check all tools if none is requested inst5 *nix (30.1s)
  √ index » check all tools if none is requested inst5 Win (28.3s)
  √ index » positive node result want0 *nix (28.2s)
  √ index » positive node result want0 Win (26.4s)
  √ index » positive node result want1 *nix (26.3s)
  √ index » positive node result want1 Win (24.5s)
  √ index » positive node result want2 *nix (24.5s)
  √ index » positive node result want2 Win (22.7s)
  √ index » positive node result want3 *nix (22.6s)
  √ index » positive node result want3 Win (20.7s)
  √ index » positive node result want4 *nix (20.7s)
  √ index » positive node result want4 Win (18.7s)
  √ index » positive node result want5 *nix (18.7s)
  √ index » positive node result want5 Win (16.7s)
  √ index » negative node result want0 *nix (16.6s)
  √ index » negative node result want0 Win (14.6s)
  √ index » negative node result want1 *nix (14.5s)
  √ index » negative node result want1 Win (12.6s)
  √ index » negative node result want2 *nix (12.5s)
  √ index » negative node result want2 Win (10.4s)
  √ index » negative node result want3 *nix (10.4s)
  √ index » negative node result want3 Win (8.3s)
  √ index » negative node result want4 *nix (8.3s)
  √ index » negative node result want4 Win (6.2s)
  √ index » negative node result want5 *nix (6.1s)
  √ index » negative node result want5 Win (4.5s)
  √ index » negative node result want6 *nix (4.4s)
  √ index » negative node result want6 Win (2.7s)
  √ index » tool not installed *nix (2.6s)
  √ index » tool not installed Win
  √ index » global versions only (57.8s)

  3 tests failed

  bin » run with npx

  c:\Users\Yuki\Documents\Projects\check-node-version\__tests__\bin.js:20

   19:   exec("npx ./bin.js --print", (error, stdout) => {
   20:     t.falsy(error);                                
   21:     t.truthy(stdout);

  Value is not falsy:

  Error {
    cmd: 'npx ./bin.js --print',
    code: 1,
    killed: false,
    signal: null,
    message: `Command failed: npx ./bin.js --print␊
    'npx' �́A�����R�}���h�܂��͊O���R�}���h�A␍␊
    ����\\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B␍␊
    `,
  }

  error
  => Error {
    cmd: 'npx ./bin.js --print',
    code: 1,
    killed: false,
    signal: null,
    message: `Command failed: npx ./bin.js --print␊
    'npx' �́A�����R�}���h�܂��͊O���R�}���h�A␍␊
    ����\\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B␍␊
    `,
  }



  bin » run with node

  c:\Users\Yuki\Documents\Projects\check-node-version\__tests__\bin.js:10

    9:   exec("node ./bin.js --print", (error, stdout) => {
   10:     t.falsy(error);                                 
   11:     t.truthy(stdout);

  Value is not falsy:

  Error {
    cmd: 'node ./bin.js --print',
    code: 1,
    killed: false,
    signal: null,
    message: `Command failed: node ./bin.js --print␊
    c:\\Users\\Yuki\\Documents\\Projects\\check-node-version\\cli.js:45␍␊
        throw err;␍␊
        ^␍␊
    ␍␊
    Error: Command failed: "npx --version"␍␊
    ␍␊
    stderr:␍␊
    'npx' �́A�����R�}���h�܂��͊O���R�}���h�A␍
    ␍␊
    ����\\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B␍␊
    ␍␊
    ␍␊
    original error message:␍␊
    Command failed: npx --version␍␊
    'npx' �́A�����R�}���h�܂��͊O���R�}���h�A␍
    ␍␊
    ����\\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B␍
    ␍␊
    ␍␊
    ␍␊
        at exec (c:\\Users\\Yuki\\Documents\\Projects\\check-node-version\\index.js:58:21)␍␊
        at ChildProcess.exithandler (child_process.js:301:5)␍␊
        at ChildProcess.emit (events.js:198:13)␍␊
        at maybeClose (internal/child_process.js:982:16)␍␊
        at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)␍␊
    `,
  }

  error
  => Error {
    cmd: 'node ./bin.js --print',
    code: 1,
    killed: false,
    signal: null,
    message: `Command failed: node ./bin.js --print␊
    c:\\Users\\Yuki\\Documents\\Projects\\check-node-version\\cli.js:45␍␊
        throw err;␍␊
        ^␍␊
    ␍␊
    Error: Command failed: "npx --version"␍␊
    ␍␊
    stderr:␍␊
    'npx' �́A�����R�}���h�܂��͊O���R�}���h�A␍
    ␍␊
    ����\\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B␍␊
    ␍␊
    ␍␊
    original error message:␍␊
    Command failed: npx --version␍␊
    'npx' �́A�����R�}���h�܂��͊O���R�}���h�A␍
    ␍␊
    ����\\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B␍
    ␍␊
    ␍␊
    ␍␊
        at exec (c:\\Users\\Yuki\\Documents\\Projects\\check-node-version\\index.js:58:21)␍␊
        at ChildProcess.exithandler (child_process.js:301:5)␍␊
        at ChildProcess.emit (events.js:198:13)␍␊
        at maybeClose (internal/child_process.js:982:16)␍␊
        at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)␍␊
    `,
  }



  bin » run npm package

  c:\Users\Yuki\Documents\Projects\check-node-version\__tests__\bin.js:36

   35:
   36:       t.falsy(error);  
   37:       t.truthy(stdout);

  Value is not falsy:

  Error {
    cmd: 'npx ./check-node-version-4.0.1.tgz --print',
    code: 1,
    killed: false,
    signal: null,
    message: `Command failed: npx ./check-node-version-4.0.1.tgz --print␊
    'npx' �́A�����R�}���h�܂��͊O���R�}���h�A␍␊
    ����\\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B␍␊
    `,
  }

  error
  => Error {
    cmd: 'npx ./check-node-version-4.0.1.tgz --print',
    code: 1,
    killed: false,
    signal: null,
    message: `Command failed: npx ./check-node-version-4.0.1.tgz --print␊
    'npx' �́A�����R�}���h�܂��͊O���R�}���h�A␍␊
    ����\\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B␍␊
    `,
  }

npm ERR! Test failed.  See above for more details.
```

**Comment by yuki-takei** [comment]
@rasenplanscher 

*test6.js*

```javascript
const {exec} = require('child_process')
let codepage = ''

exec('chcp', (_,stdout) => {
	codepage = stdout.match(/\d+/)[0]
	exec('chcp 65001', () => {
		exec('nxp --version', (err) => { 
			console.error(err.message)
			exec(`chcp ${codepage}`)
		})
	})
})
```

This was same to test5-1.js.

```
>nxp --version
'nxp' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。

>chcp
現在のコード ページ: 932

>node test6.js

>chcp
現在のコード ページ: 932
```

**Comment by rasenplanscher** [comment]
I'm still on this and not happy with the solution yet.

Please, try this:
```js
const {exec} = require('child_process')
let codepage = ''

exec('chcp', (_,stdout) => {
	codepage = stdout.match(/\d+/)[0]
	exec('chcp 65001', () => {
		exec('nxp --version', (err) => {
			exec(`chcp ${codepage}`, () => {
				console.error(err.message)
				setImmediate(() => console.error(err.message))
				setTimeout(() => console.error(err.message))
				setTimeout(() => console.error(err.message), 250)
				setTimeout(() => console.error(err.message), 2500)
			})
		})
	})
})

```

Ideally, this should output the error 5 times. However, due to the previous tests, I'm not sure 😅
